name: Task Template
description: Create a new task for the project
title: "Scope - task name"
labels: 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a task! Please fill out the information below.
 
 
 - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the task
      placeholder: |
        Please include:
        What? 
       - Objectives that needsto be done
       - Any specific requirements or constraints
       
        Why?
        - Why it's needed

        Who? 
        - Targeted audiences for this task

        How? 
        - Which methodology will be used ? 

        Where? 
        - Where do we handle this task

        When? 
        
    validations:
      required: true 


        - type: textarea
    id: todo-list
    attributes:
      label: To-do list
      description: List the actions that must be met for this task to be considered complete
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

