name: Task Template
description: Create a new task for the project
title: "Scope - task name"
labels: []  # Empty array for labels
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a task! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the task
      value: |
        ## What? 
        - Objectives that needs to be done:
          - 
        - Requirements or constraints:
          - 
        
        ## Why?
        - Why it's needed:
          - 

        ## Who? 
        - Targeted audiences for this task:
          - 

        ## How? 
        - Methodology to be used:
          - 

        ## Where? 
        - Where we handle this task:
          - 

        ## When? 
        - Timeline/Deadline:
          - 
      placeholder: Please fill in the details under each section
    validations:
      required: true

  - type: textarea
    id: todo-list
    attributes:
      label: To-do list
      description: List the actions that must be met for this task to be considered complete
      value: |
        - [ ] Planning Phase
          - [ ] Define requirements
          - [ ] Create timeline
        - [ ] Implementation Phase
          - [ ] Task implementation
          - [ ] Review implementation
        - [ ] Testing Phase
          - [ ] Test functionality
          - [ ] Document results
      placeholder: Add or modify tasks as needed
    validations:
      required: true
